---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, message = FALSE, echo = FALSE}

library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(ggplot2)

```

```{r import data, message = FALSE, echo = FALSE}

data("ny_noaa") 

```

```{r tidy data, message = FALSE}

set.seed(8) 

ny_noaa <-
  ny_noaa %>%
  sample_n(99999) %>%
  janitor::clean_names() %>% 
  drop_na() %>% 
  separate(col = date, 
           into = c("year","month", "day")) %>%
  mutate(across(.cols
                = c(year, month, day), as.integer)) %>%
  mutate(month = month.name[month]) %>%
  mutate(prcp = prcp/10, 
         tmax = as.integer(tmax)/10,
         tmin = as.integer(tmin)/10)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Boxplot

```{r message = FALSE}

ny_noaa %>%
  mutate(month = 
           fct_reorder(month, tmin)) %>%
  group_by(year, month, id) %>%
  summarize(mean_tmin = mean(tmin)) %>%
  plot_ly(x = ~ month, 
          y = ~ round(mean_tmin, digits = 0), 
          color = ~ month, 
          alpha = 0.6,
          type = "box",
          colors = "inferno") %>%
  layout(
    title = 
      "Average Minimum Temperature per Month", 
    xaxis = list(title = "Month"),
    yaxis = list(title = "Mean Minimum Temperature (Celcius)")) 

```

Column {data-width=350}
-----------------------------------------------------------------------

### Bar Graph

```{r warning = FALSE}

ny_noaa %>%
  count(snwd) %>% 
  filter(snwd > 0) %>% 
  plot_ly(x = ~ snwd, 
          y = ~ n, 
          type = "bar", 
          color = "inferno") %>%
  layout(
    title = 
      "Snow Depth Count (Snow Days Only)", 
    xaxis = list(title = "Snow Depth (mm)"),
    yaxis = list(title = "Count (n)"))

```

### Scatterplot

```{r scatter plot, message = FALSE}

ny_noaa %>%
  filter(year == 2010) %>%
  mutate(text_label = str_c("Max Temperature: ", tmax, 
                            ", Min Temperature: ", tmin, 
                            ", Date: ", month," ", day,", ", year)) %>%
  plot_ly(x = ~ tmin, 
          y = ~ tmax,
          alpha = 0.6,
          color = ~ month,
          colors = "inferno", 
          text = ~ text_label) %>%
  layout(title = 
           "Minimum Temperature versus Maximum Temperature (2010)",
         xaxis = list(title = "Minimum temperature (Celcius)"),
         yaxis = list(title = "Maximum temperature (Celcius)"))

```
