---
title: "Plotly"
output: html_document
---

```{r setup, message = FALSE, echo = FALSE}

library(tidyverse)
library(p8105.datasets)
library(plotly)
library(ggplot2)

```

```{r import data, message = FALSE, echo = FALSE}

data("ny_noaa") 

```

```{r tidy data, message = FALSE}

set.seed(8) 

ny_noaa <-
  ny_noaa %>%
  sample_n(99999) %>%
  janitor::clean_names() %>% 
  drop_na() %>% 
  separate(col = date, 
           into = c("year","month", "day")) %>%
  mutate(across(.cols
                = c(year, month, day), as.integer)) %>%
  mutate(month = month.name[month]) %>%
  mutate(prcp = prcp/10, 
         tmax = as.integer(tmax)/10,
         tmin = as.integer(tmin)/10,
         #tmin_rounded = round(tmin, digits = 1))

```


### Bar Graph

```{r}

ny_noaa %>%
  select(snow, date) %>%
  group_by(date) %>%
  summarise(mean = mean(snow)) %>%
  mutate(date = fct_reorder(date, snow)) %>%
  plot_ly(x = ~date, 
          y = ~snow, 
          type = "bar", 
          colors = "inferno") %>%
  layout(
    title = 
      "Average Snowfall per Month", 
    xaxis = list(title = "Month"),
    yaxis = list(title = "Snowfall in mm")) 

```

### Scatterplot

```{r scatter plot, message = FALSE}

ny_noaa %>%
  drop_na(tmin, tmax) %>%
  filter(year == 2010) %>%
  mutate(text_label = str_c("Max Temperature: ", tmax, 
                            ", Min Temperature: ", tmin, 
                            ", Date: ", month," ", day,", ", year)) %>%
  plot_ly(x = ~ tmin, 
          y = ~ tmax,
          alpha = 0.6,
          color = ~ month,
          colors = "inferno", 
          text = ~ text_label) %>%
  layout(title = 
           "Minimum Temperature versus Maximum Temperature (2010)",
         xaxis = list(title = "Minimum temperature in Celcius"),
         yaxis = list(title = "Maximum temperature in Celcius"))

```


### Boxplot

```{r message = FALSE}

ny_noaa %>%
  mutate(month = 
           fct_reorder(month, tmin)) %>%
  group_by(year, month, id) %>%
  summarize(mean_tmin = mean(tmin)) %>%
  plot_ly(x = ~ month, 
          y = ~ factor(mean_tmin), 
          color = ~ month, 
          alpha = 0.6,
          type = "box",
          colors = "inferno") %>%
  layout(
    title = 
      "Average Minimum Temperature per Month", 
    xaxis = list(title = "Month"),
    yaxis = list(title = "Mean Minimum Temperature in Celcius")) 

```

<br>
<center>

Click here to return to the [main](index.html) page.